export const RECORDS_GROUPS = [
  {
    label: 'Vitals',
    value: 'vitals',
  },
  {
    label: 'Chief Complaint',
    value: 'chief-complaint',
  },
  {
    label: 'History of Present Illness',
    value: 'history-of-present-illness',
  },
  {
    label: 'Past Medical History',
    value: 'past-medical-history',
  },
  {
    label: 'Family History',
    value: 'family-history',
  },
  {
    label: 'Social History',
    value: 'social-history',
  },
  {
    label: 'Allergy History',
    value: 'allergy-history',
  },
  {
    label: 'Birth History',
    value: 'birth-history',
  },
  {
    label: 'Gynecological History',
    value: 'gynecological-history',
  },
  {
    label: 'Hospitalization History',
    value: 'hospitalization-history',
  },
  {
    label: 'Immunication History',
    value: 'immunication-history',
  },
  {
    label: 'Menstrual History',
    value: 'menstrual-history',
  },
  {
    label: 'Obstetric History',
    value: 'obstetric-history',
  },
  {
    label: 'Surgical History',
    value: 'surgical-history',
  },
  {
    label: 'Dental History',
    value: 'dental-history',
  },
  {
    label: 'Review of Systems',
    value: 'review-of-systems',
  },
  {
    label: 'ENT Notes',
    value: 'ent-notes',
  },
  {
    label: 'Physical Examination',
    value: 'physical-examination',
  },
  {
    label: 'Impression',
    value: 'impression',
  },
  {
    label: 'Care Plan Notes',
    value: 'care-plan-notes',
  },
  {
    label: 'Prescription',
    value: 'prescription',
  },
  {
    label: 'Lab Test',
    value: 'lab-test',
  },
  {
    label: 'Imaging Test',
    value: 'imaging-test',
  },
  {
    label: 'Medical Procedure',
    value: 'medical-procedure',
  },
  {
    label: 'Medical Procedure Order',
    value: 'medical-procedure-order',
  },
  {
    label: 'Attachment',
    value: 'attachment',
  },
  {
    label: 'Medical Certificate',
    value: 'medical-certificate',
  },
  {
    label: 'Fitness Certificate',
    value: 'fitness-certificate',
  },
  {
    label: 'Waiver',
    value: 'waiver',
  },
  {
    label: 'Claim Form',
    value: 'claim-form',
  },
  {
    label: 'General Form',
    value: 'general-form',
  },
];

export const PME_EMR_CONFIG = [
  {
    name: 'Vitals',
    type: 'vitals',
    disableFieldValue: true,
    fields: [
      { field: 'createdAt', name: 'Date Created' },
      { field: 'takenAt', name: 'Taken At' },
      { field: 'weight', name: 'Weight' },
      { field: 'height', name: 'Height' },
      { field: 'bmi', name: 'BMI' },
      { field: 'bpSystolic', name: 'BP Systolic' },
      { field: 'bpDiastolic', name: 'BP Diastolic' },
      { field: 'pulse', name: 'Pulse' },
      { field: 'respiration', name: 'Respiration' },
      { field: 'temperature', name: 'Temperature' },
      { field: 'temperatureMethod', name: 'Temperature Method' },
      { field: 'headCircumference', name: 'Head Circumference' },
      { field: 'waistCircumference', name: 'Waist Circumference' },
      { field: 'neckCircumference', name: 'Neck Circumference' },
      { field: 'abdominalCircumference', name: 'Abdominal Circumference' },
      { field: 'chestCircumference', name: 'Chest Circumference' },
      { field: 'chestInspiration', name: 'Chest Inspiration' },
      { field: 'chestExpiration', name: 'Chest Expiration' },
      { field: 'o2sats', name: 'O2 Sats' },
      { field: 'lmp', name: 'Last Menstrual Period' },
      { field: 'visualAcuityDsntUncorrectL', name: 'Distant Uncorrected (L)' },
      { field: 'visualAcuityDsntUncorrectR', name: 'Distant Uncorrected (R)' },
      { field: 'visualAcuityDsntCorrectL', name: 'Distant Corrected (L)' },
      { field: 'visualAcuityDsntCorrectR', name: 'Distant Corrected (R)' },
      { field: 'visualAcuityNearUncorrectL', name: 'Near Uncorrected (L)' },
      { field: 'visualAcuityNearUncorrectR', name: 'Near Uncorrected (R)' },
      { field: 'visualAcuityNearCorrectL', name: 'Near Corrected (L)' },
      { field: 'visualAcuityNearCorrectR', name: 'Near Corrected (R)' },
      { field: 'visualAcuityVisionNormal', name: 'Color Vision (Normal)' },
      { field: 'visualAcuityVisionAbnormal', name: 'Color Vision (Abnormal)' },
      { field: 'visualAcuityLeft', name: 'Vision Acuity (L)' },
      { field: 'visualAcuityRight', name: 'Vision Acuity (R)' },
      { field: 'visualRemarks', name: 'Vision Remarks' },
      { field: 'colorVision', name: 'Color Vision' },
    ],
  },
  {
    name: 'Chief Complaint',
    type: 'chief-complaint',
    fields: [
      { field: 'text', name: 'Chief Complaint' },
    ],
  },
  {
    name: 'History of Present Illness',
    type: 'hpi',
    fields: [
      { field: 'text', name: 'History of Present Illness' },
    ],
  },
  {
    name: 'Past Medical History',
    type: 'medical-history',
    fields: [
      { field: 'createdAt', name: 'Date Created', disableFieldValue: true },
      { field: 'medicalCondition', name: 'Medical Condition' },
      { field: 'medicalConditionYear', name: 'Date Occured' },
      { field: 'notes', name: 'Remarks' },
    ],
  },
  {
    name: 'Family History',
    type: 'family-history',
    fields: [
      { field: 'createdAt', name: 'Date Created', disableFieldValue: true },
      { field: 'medicalCondition', name: 'Medical Condition' },
      { field: 'medicalConditionAt', name: 'Date Occured', disableFieldValue: true },
      { field: 'relationship', name: 'Relationship' },
      { field: 'notes', name: 'Remarks' },
    ],
  },
  {
    name: 'Social History',
    type: 'social-history',
    disableFieldValue: true,
    fields: [
      { field: 'createdAt', name: 'Date Created' },
      { field: 'exercises', name: 'Exercising?' },
      { field: 'drinksAlcohol', name: 'Drinking Alcohol?' },
      { field: 'drinksAlcoholRemarks', name: 'Drinking Details' },
      { field: 'smoking', name: 'Smoking?' },
      { field: 'smokingSticksPerDay', name: 'Sticks per day' },
      { field: 'smokingYears', name: 'Years smoking' },
      { field: 'usesProhibitedDrugs', name: 'Uses prohibited drugs?' },
      { field: 'drugName', name: 'Drug name' },
      { field: 'drugLastUsedAt', name: 'Date occurred' },
      { field: 'sexuallyActive', name: 'Sexually Active?' },
      { field: 'numOfSexualPartners', name: 'No. of sexual partners' },
      { field: 'educationalLevel', name: 'Educational level' },
      { field: 'others', name: 'Others' },
    ],
  },
  {
    name: 'Allergy History',
    type: 'allergy',
    fields: [
      { field: 'createdAt', name: 'Date Created', disableFieldValue: true },
      { field: 'name', name: 'Allergy' },
      { field: 'startedAt', name: 'Date Occurred', disableFieldValue: true },
      { field: 'description', name: 'Notes' },
      { field: 'supplement', name: 'Supplement' },
    ],
  },
  {
    name: 'Birth History',
    type: 'birth-history',
    fields: [
      { field: 'createdAt', name: 'Date Created', disableFieldValue: true },
      { field: 'methodOfDelivery', name: 'Method of delivery' },
      { field: 'deliveredAt', disableFieldValue: true },
      { field: 'attendedBy', name: 'Attended by' },
      { field: 'complications', name: 'Complications' },
      { field: 'notes', name: 'Remarks' },
    ],
  },
  {
    name: 'Gynecological History',
    type: 'gynecological-history',
    fields: [
      { field: 'createdAt', name: 'Date Created', disableFieldValue: true },
      { field: 'prevCervicSmearsResult', name: 'Previous Cervix Smears Result' },
      { field: 'prevCervicSmearsDate', name: 'Previous Cervix Smears Date', disableFieldValue: true },
      { field: 'prevProblemsTreatments', name: 'Previous Problems/Treatments' },
      { field: 'currentContraception', name: 'Current Contraception' },
      { field: 'notes', name: 'Remarks' },
    ],
  },
  {
    name: 'Hospitalization History',
    type: 'hospitalization-history',
    fields: [
      { field: 'createdAt', name: 'Date Created', disableFieldValue: true },
      { field: 'hospitalizedAt', name: 'Hospitalization date', disableFieldValue: true },
      { field: 'hospitalName', name: 'Hospital name' },
      { field: 'diagnosis', name: 'Diagnosis' },
      { field: 'treatment', name: 'Treatment' },
      { field: 'notes', name: 'Remarks' },
    ],
  },
  {
    name: 'Immunization/Vaccination History',
    type: 'vaccination',
    fields: [
      { field: 'createdAt', name: 'Date Created', disableFieldValue: true },
      { field: 'vaccine', name: 'Vaccine' },
      { field: 'injectionSite', name: 'Injection Site' },
      { field: 'administeredBy', name: 'Administered by' },
      { field: 'administeredAt', name: 'Date Administered', disableFieldValue: true },
      { field: 'lotNo', name: 'Lot no' },
      { field: 'expiresAt', name: 'Expiration Date', disableFieldValue: true },
      { field: 'group', name: 'Group' },
    ],
  },
  {
    name: 'Menstrual History',
    type: 'menstrual-history',
    fields: [
      { field: 'createdAt', name: 'Date Created', disableFieldValue: true },
      { field: 'menarche', name: 'Menarche' },
      { field: 'interval', name: 'Interval' },
      { field: 'duration', name: 'Duration' },
      { field: 'amount', name: 'Amount' },
      { field: 'notes', name: 'Remarks' },
      { field: 'LMP', name: 'LMP' },
      { field: 'cycle', name: 'Cycle' },
      { field: 'OBScore', name: 'OB Score' },
    ],
  },
  {
    name: 'Obstetric History',
    type: 'obstetric-history',
    fields: [
      { field: 'createdAt', name: 'Date Created', disableFieldValue: true },
      { field: 'LMPDate', name: 'LMP Date' },
      { field: 'PMPDate', name: 'PMP Date' },
      { field: 'gravidity', name: 'Gravidity' },
      { field: 'parity', name: 'Parity' },
      { field: 'notes', name: 'Remarks' },
    ],
  },
  {
    name: 'Surgical History',
    type: 'surgical-history',
    fields: [
      { field: 'createdAt', name: 'Date Created', disableFieldValue: true },
      { field: 'performedAt', name: 'Date performed', disableFieldValue: true },
      { field: 'hospitalName', name: 'Hospital name' },
      { field: 'procedure', name: 'Procedure' },
      { field: 'notes', name: 'Remarks' },
    ],
  },
  {
    name: 'Dental History',
    type: 'dental-history',
    disableFieldValue: true,
    fields: [
      { field: 'gingivae', name: 'Gingivae' },
      { field: 'palate', name: 'Palate' },
      { field: 'frenum', name: 'Frenum' },
      { field: 'profile', name: 'Profile' },
      { field: 'hygiene', name: 'Hygiene' },
      { field: 'abrasions', name: 'Abrasions' },
      { field: 'recededGums', name: 'Receded Gums' },
      { field: 'mouthOpening', name: 'Mouth Opening' },
      { field: 'oropharynx', name: 'Oropharynx' },
      { field: 'teethDiscoloration', name: 'Teeth Discoloration' },
      { field: 'calculus', name: 'Calculus' },
      { field: 'tongue', name: 'Tongue' },
      { field: 'malocclusion', name: 'Malocclusion' },
      { field: 'mentalis', name: 'Mentalis' },
      { field: 'swallowing', name: 'Swallowing' },
      { field: 'gagFlex', name: 'GagFlex' },
      { field: 'prevDentist', name: 'Previous Dentist' },
      { field: 'prevDentistContactNo', name: 'Previous Dentist Contact No' },
    ],
  },
  {
    name: 'Review of Systems',
    type: 'ros',
    disableFieldValue: true,
    fields: [
      { field: 'general', name: 'General - Remarks' },
      { field: 'generalStatus', name: 'General - Status' },
      { field: 'skin', name: 'Skin - Remarks' },
      { field: 'skinStatus', name: 'Skin - Status' },
      { field: 'ent', name: 'ENT - Remarks' },
      { field: 'entStatus', name: 'ENT - Status' },
      { field: 'eyes', name: 'Eyes - Remarks' },
      { field: 'eyesStatus', name: 'Eyes - Status' },
      { field: 'neck', name: 'Neck - Remarks' },
      { field: 'neckStatus', name: 'Neck - Status' },
      { field: 'breasts', name: 'Breasts - Remarks' },
      { field: 'breastsStatus', name: 'Breasts - Status' },
      { field: 'respiratory', name: 'Respiratory - Remarks' },
      { field: 'respiratoryStatus', name: 'Respiratory - Status' },
      { field: 'cardiovascular', name: 'Cardiovascular - Remarks' },
      { field: 'cardiovascularStatus', name: 'Cardiovascular - Status' },
      { field: 'gastrointestinal', name: 'Gastrointestinal - Remarks' },
      { field: 'gastrointestinalStatus', name: 'Gastrointestinal - Status' },
      { field: 'peripheralVascular', name: 'Veripheral Vascular - Remarks' },
      { field: 'peripheralVascularStatus', name: 'Veripheral Vascular - Status' },
      { field: 'genitourinary', name: 'Genitourinary - Remarks' },
      { field: 'genitourinaryStatus', name: 'Genitourinary - Status' },
      { field: 'musculoskeletal', name: 'Musculoskeletal - Remarks' },
      { field: 'musculoskeletalStatus', name: 'Musculoskeletal - Status' },
      { field: 'psychiatric', name: 'Psychiatric - Remarks' },
      { field: 'psychiatricStatus', name: 'Psychiatric - Status' },
      { field: 'neurologic', name: 'Neurologic - Remarks' },
      { field: 'neurologicStatus', name: 'Neurologic - Status' },
      { field: 'hematologicLymphatic', name: 'Hematologic Lymphatic - Remarks' },
      { field: 'hematologicLymphaticStatus', name: 'Hematologic Lymphatic - Status' },
      { field: 'endocrine', name: 'Endocrine - Remarks' },
      { field: 'endocrineStatus', name: 'Endocrine - Status' },
    ],
  },
  {
    name: 'ENT Note',
    type: 'ent-note',
    disableFieldValue: true,
    fields: [
      { field: 'createdAt', name: 'Date Created' },
      { field: 'cpapPressure', name: 'CPAP Pressure' },
      { field: 'bipapInspiration', name: 'BPAP Inspiration' },
      { field: 'bipapExpiration', name: 'BPAP Expiration' },
      { field: 'lsatPressure', name: 'LSAT Pressure' },
      { field: 'ahi', name: 'AHI' },
      { field: 'rampTime', name: 'Ramp Time' },
      { field: 'psgDiagnostic', name: 'PSH Diagnostic' },
      { field: 'psgTherapeutic', name: 'PSG Therapeutic' },
      { field: 'psgSplit', name: 'PSG Split' },
    ],
  },
  {
    name: 'Physical Exam',
    type: 'physical-exam',
    disableFieldValue: true,
    fields: [
      { field: 'general.text', name: 'General - Remarks' },
      { field: 'general.status', name: 'General - Status' },
      { field: 'head.text', name: 'Head - Remarks' },
      { field: 'head.status', name: 'Head - Status' },
      { field: 'eyes.text', name: 'Eyes - Remarks' },
      { field: 'eyes.status', name: 'Eyes - Status' },
      { field: 'ears.text', name: 'Ears - Remarks' },
      { field: 'ears.status', name: 'Ears - Status' },
      { field: 'nose.text', name: 'Nose - Remarks' },
      { field: 'nose.status', name: 'Nose - Status' },
      { field: 'neck.text', name: 'Neck - Remarks' },
      { field: 'neck.status', name: 'Neck - Status' },
      { field: 'throat.text', name: 'Throat - Remarks' },
      { field: 'throat.status', name: 'Throat - Status' },
      { field: 'breathSounds.text', name: 'Breath Sounds - Remarks' },
      { field: 'breathSounds.status', name: 'Breath Sounds - Status' },
      { field: 'respiratory.text', name: 'Respiratory - Remarks' },
      { field: 'respiratory.status', name: 'Respiratory - Status' },
      { field: 'cardiovascular.text', name: 'Cardiovascular - Remarks' },
      { field: 'cardiovascular.status', name: 'Cardiovascular - Status' },
      { field: 'breasts.text', name: 'Breasts - Remarks' },
      { field: 'breasts.status', name: 'Breasts - Status' },
      { field: 'chest.text', name: 'Chest - Remarks' },
      { field: 'chest.status', name: 'Chest - Status' },
      { field: 'back.text', name: 'Back - Remarks' },
      { field: 'back.status', name: 'Back - Status' },
      { field: 'abdomen.text', name: 'Abdomen - Remarks' },
      { field: 'abdomen.status', name: 'Abdomen - Status' },
      { field: 'gastrointestinal.text', name: 'Gastrointestinal - Remarks' },
      { field: 'gastrointestinal.status', name: 'Gastrointestinal - Status' },
      { field: 'genitourinary.text', name: 'Genitourinary - Remarks' },
      { field: 'genitourinary.status', name: 'Genitourinary - Status' },
      { field: 'musculoskeletal.text', name: 'Musculoskeletal - Remarks' },
      { field: 'musculoskeletal.status', name: 'Musculoskeletal - Status' },
      { field: 'skin.text', name: 'Skin - Remarks' },
      { field: 'skin.status', name: 'Skin - Status' },
      { field: 'endocrine.text', name: 'Endocrine - Remarks' },
      { field: 'endocrine.status', name: 'Endocrine - Status' },
      { field: 'psychiatric.text', name: 'Psychiatric - Remarks' },
      { field: 'psychiatric.status', name: 'Psychiatric - Status' },
      { field: 'hematologicLymphatic.text', name: 'Hematologic Lymphatic - Remarks' },
      { field: 'hematologicLymphatic.status', name: 'Hematologic Lymphatic - Status' },
      { field: 'allergicImmunologic.text', name: 'Allergic Immunologic - Remarks' },
      { field: 'allergicImmunologic.status', name: 'Allergic Immunologic - Status' },
      { field: 'extermities.text', name: 'Extermities - Remarks' },
      { field: 'extermities.status', name: 'Extermities - Status' },
      { field: 'neurologic.text', name: 'Neurologic - Remarks' },
      { field: 'neurologic.status', name: 'Neurologic - Status' },
      { field: 'rectal.text', name: 'Rectal - Remarks' },
      { field: 'rectal.status', name: 'Rectal - Status' },
      { field: 'genitalia.text', name: 'Genitalia - Remarks' },
      { field: 'genitalia.status', name: 'Genitalia - Status' },
    ],
  },
  {
    name: 'Impression',
    type: 'assessment',
    subtype: 'impression',
    fields: [
      { field: 'createdAt', name: 'Date Created', disableFieldValue: true },
      { field: 'text', name: 'Impression' },
    ],
  },
  // {
  //   "name": "Diagnosis",
  //   "type": "assessment",
  //   "subtype": "diagnosis",
  //   "fields": [
  //     { "field": "createdAt", "name": "Date Created", "disableFieldValue": true },
  //     { "field": "text" },
  //   ],
  // },

  {
    name: 'Care Plan Notes',
    type: 'care-plan',
    fields: [
      { field: 'createdAt', name: 'Date Created', disableFieldValue: true },
      { field: 'text', name: 'Care Plan Notes' },
    ],
  },
  {
    name: 'Prescription',
    type: 'medication-order',
    disableFieldValue: true,
    fields: [
      { field: 'createdAt', name: 'Date Created' },
      { field: 'items', name: 'Medicines' },
    ],
  },
  {
    name: 'Laboratory Order',
    type: 'lab-test-order',
    disableFieldValue: true,
    fields: [
      { field: 'createdAt', name: 'Date Created' },
      { field: 'reason', name: 'Reason' },
      { field: 'tests', name: 'Tests' },
      { field: 'icd10', name: 'ICD10' },
    ],
  },
  {
    name: 'Imaging Order',
    type: 'imaging-test-order',
    disableFieldValue: true,
    fields: [
      { field: 'createdAt', name: 'Date Created' },
      { field: 'reason', name: 'Reason' },
      { field: 'tests', name: 'Tests' },
      { field: 'icd10', name: 'ICD10' },
    ],
  },
  {
    name: 'Medical Procedure',
    type: 'medical-procedure',
    disableFieldValue: true,
    fields: [
      { field: 'createdAt', name: 'Date Created' },
      { field: 'notes', name: 'Remarks' },
      { field: 'name', name: 'Procedure' },
      { field: 'icd10', name: 'ICD10' },
      { field: 'providers', name: 'Attending Staff' },
    ],
  },
  {
    name: 'Medical Procedure Order',
    type: 'medical-procedure-order',
    disableFieldValue: true,
    fields: [
      { field: 'createdAt', name: 'Date Created' },
      { field: 'notes', name: 'Remarks' },
      { field: 'name', name: 'Procedure' },
      { field: 'icd10', name: 'ICD10' },
      { field: 'providers', name: 'Attending Staff' },
    ],
  },

  {
    name: 'Attachments',
    type: 'attachment',
    disableFieldValue: true,
    fields: [
      { field: 'createdAt', name: 'Date Created' },
      { field: 'title', name: 'Title' },
      { field: 'description', name: 'Description' },
      { field: 'attachmentURLs', name: 'Attachments' },
    ],
  },
  {
    name: 'Medical Certificate',
    type: 'med-certificate',
    disableFieldValue: true,
    fields: [
      { field: 'createdAt', name: 'Date Created' },
      { field: 'template', name: 'Template' },
      { field: 'data', name: 'Data' },
    ],
  },
  {
    name: 'Fitness Certification',
    type: 'fit-certificate',
    disableFieldValue: true,
    fields: [
      { field: 'createdAt', name: 'Date Created' },
      { field: 'template', name: 'Template' },
      { field: 'data', name: 'Data' },
    ],
  },
  {
    name: 'Waiver',
    type: 'waiver',
    disableFieldValue: true,
    fields: [
      { field: 'createdAt', name: 'Date Created' },
      { field: 'template', name: 'Template' },
      { field: 'data', name: 'Data' },
    ],
  },
  {
    name: 'Claim Forms',
    type: 'claims',
    disableFieldValue: true,
    fields: [
      { field: 'createdAt', name: 'Date Created' },
      { field: 'template', name: 'Template' },
      { field: 'data', name: 'Data' },
    ],
  },
  {
    name: 'General Forms',
    type: 'med-certificate',
    disableFieldValue: true,
    fields: [
      { field: 'createdAt', name: 'Date Created' },
      { field: 'template', name: 'Template' },
      { field: 'data', name: 'Data' },
    ],
  },
];
