export const PME_REPORT_MEDICAL_RECORDS_TOKENS = [
  'patient_complaint', 'patient_hpi', 'patient_pmhx', 'patient_fhx', 'patient_shx', 'sh_is_exercising',
  'sh_is_smoking', 'sh_smoking_sticks_per_day', 'sh_smoking_pack_years', 'sh_is_drinking', 'sh_drinking_remarks',
  'sh_is_using_drugs', 'sh_prohibited_drugs', 'patient_allergies_hx',
  'patient_allergy_name', 'patient_allergy_supplement', 'patient_birth_hx', 'patient_gynecological_hx', 'patient_hospitalization_hx', 'patient_vaccination_hx',
  'patient_menstrual_hx', 'patient_menstrual_lmp', 'patient_menstrual_interval', 'patient_menstrual_duration', 'patient_menstrual_cycle', 'patient_menstrual_obscore',
  'patient_obstetric_hx', 'patient_surgical_hx', 'patient_dental_hx', 'patient_ros', 'ros_status_general', 'ros_general', 'ros_status_eyes', 'ros_eyes',
  'ros_status_skin', 'ros_skin', 'ros_status_ent', 'ros_ent', 'ros_status_neck', 'ros_neck', 'ros_status_breasts', 'ros_breasts', 'ros_status_respiratory',
  'ros_respiratory', 'ros_status_cardiovascular', 'ros_cardiovascular', 'ros_status_gastrointestinal', 'ros_gastrointestinal', 'ros_status_peripheral_vascular',
  'ros_peripheral_vascular', 'ros_status_genitourinary', 'ros_genitourinary', 'ros_status_musculoskeletal', 'ros_musculoskeletal', 'ros_status_psychiatric',
  'ros_psychiatric', 'ros_status_neurologic', 'ros_neurologic', 'ros_status_hematologic_lymphatic', 'ros_hematologic_lymphatic', 'ros_status_endocrine',
  'ros_endocrine', 'ros_status_allergic_immunologic', 'ros_allergic_immunologic', 'pe_general_status', 'pe_general_text',
  'pe_head_status', 'pe_head_text', 'pe_eyes_status', 'pe_eyes_text', 'pe_ears_status', 'pe_ears_text', 'pe_nose_status',
  'pe_nose_text', 'pe_neck_status', 'pe_neck_text', 'pe_throat_status', 'pe_throat_text', 'pe_breath_sounds_status',
  'pe_breath_sounds_text', 'pe_respiratory_status', 'pe_respiratory_text', 'pe_cardiovascular_status', 'pe_cardiovascular_text',
  'pe_breasts_status', 'pe_breasts_text', 'pe_chest_status', 'pe_chest_text', 'pe_back_status', 'pe_back_text', 'pe_abdomen_status',
  'pe_abdomen_text', 'pe_gastrointestinal_status', 'pe_gastrointestinal_text', 'pe_genitourinary_status', 'pe_genitourinary_text',
  'pe_musculoskeletal_status', 'pe_musculoskeletal_text', 'pe_skin_status', 'pe_skin_text', 'pe_endocrine_status',
  'pe_endocrine_text', 'pe_psychiatric_status', 'pe_psychiatric_text', 'pe_hematologic_status', 'pe_hematologic_text',
  'pe_allergicImmunologic_status', 'pe_allergicImmunologic_text', 'pe_extermities_status', 'pe_extermities_text',
  'pe_neurologic_status', 'pe_neurologic_text', 'pe_rectal_status', 'pe_rectal_text', 'pe_genitalia_status', 'pe_genitalia_text',
  'patient_vitals', 'vital_height', 'vital_ht_ft', 'vital_weight', 'vital_wt_lbs', 'vital_bmi', 'vital_pulse_rate',
  'vital_resp_rate', 'vital_blood_pressure', 'vital_temperature', 'vital_visual_acuity_left', 'vital_visual_acuity_right',
  'vital_visual_remarks', 'vital_color_vision', 'patient_ent_note', 'patient_ob_note',
  'patient_physical_exam', 'patient_impression', 'patient_diagnosis', 'diagnosis_icd10', 'patient_care_plan',
  'patient_medication_order', 'patient_lab_order', 'patient_imaging_order', 'patient_medical_procedure_orders',
  'patient_medical_procedures', 'dental_note_result_table', 'patient_name', 'patient_full_name_mid_name', 'patient_sex', 'patient_age', 'patient_first_name',
  'patient_middle_name', 'patient_last_name', 'patient_dob', 'patient_blood_type', 'patient_mobile_no', 'patient_marital_status',
  'patient_full_address', 'patient_osca_id', 'patient_pwd_id', 'patient_hmos', 'patient_hmo_accountno', 'patient_hmo_validity',
  'patient_hmo_expiry', 'patient_hmo_status', 'patient_companies', 'patient_company_accountno', 'patient_dp', 'patient_lg_dp', 'patient_xl_dp',
  'patient_full_width_dp', 'custom_text', 'custom_choices',
];
